name: docker_push_aspnet
on:
  push:
    branches: [ main ]
    paths:
      - "HealthChecksAspNet"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: publish
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u daniellarsennz --password-stdin
          docker build . -f HealthChecksAspNet.Dockerfile -t "daniellarsennz/healthchecksaspnet:latest" -t "daniellarsennz/healthchecksaspnet:${{ github.sha }}"
          docker push "daniellarsennz/healthchecksaspnet:latest"
        shell: bash
