name: docker_push_functions
on:
  push:
    branches: [ main ]
    paths:
      - "HealthChecksAzureFunctions/**"
      - "HealthChecksCommon/**"
      - "HealthChecksAzureFunctions.Dockerfile"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: publish
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u daniellarsennz --password-stdin
          docker build . -f HealthChecksAzureFunctions.Dockerfile -t "daniellarsennz/healthchecksazurefunctions:latest" -t "daniellarsennz/healthchecksazurefunctions:${{ github.sha }}" --build-arg "GITHUB_SHA=${{ github.sha }}"
          docker push "daniellarsennz/healthchecksazurefunctions:latest"
        shell: bash
